## Redis 哨兵配置
spring:
  redis:
    password: foo
    database: 0
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 192.168.49.144:26382,192.168.49.152:26380,192.168.49.153:26381
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1
        time-between-eviction-runs: -1
        min-evictable-idle-time-millis: 1800000
        num-tests-pereviction-run: 3
        test-on-borrow: true
        test-while-idle: true